#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt', '>= 1.5.0'
cookbook 'build-essential', '>= 1.2.0'
cookbook 'couchdb', '>= 1.0.4'
cookbook 'vim'

cookbook 'nodejs',
   :git => 'https://github.com/mdxp/nodejs-cookbook.git'
#  :ref => ''
